---
apiVersion: v1
kind: Namespace
metadata:
  name: canary-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: javawebappdeploymentv1
 namespace: canary-ns
 labels:
   app: mavenwebapp
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenwebapp
     version: v1.0.0
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebapp
      image: 838127586179.dkr.ecr.us-east-1.amazonaws.com/ecr-cicd:139
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
    imagePullSecrets:
    - name: ecr-registry-secret
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
 namespace: canary-ns
 labels:
   app: mavenwebapp
   version: v1.0.0
spec:
  type: ClusterIP
  selector:
   app: mavenwebapp
  ports:
   - port: 80
     targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mavenwebapp
  namespace: canary-ns
  labels:
    app: mavenwebapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: canary-depolyment.baladevopsforyou.com  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mavenwebappsvc
                port:
                  number: 80
---
